nome = input ('Nome = ')
print ('Qual é dia, mês e ano do seu nascimento ?')
dia = input ('Dia = ')
mes = input ('Mes = ')
ano = input ('Ano = ')
print (' É um grande prazer em te conhecer', nome,' é muito interessante em saber que você nasceu no dia ',dia, ' do mês ',mes, ' no ano de ',ano, '!')
